### ISSUE TITLE
vue-identicon fails to decode address length on polkadot icon

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/vue-ui#19]
![image](https://user-images.githubusercontent.com/5887929/67389276-91b77980-f59a-11e9-84db-7cb1c884a70b.png)

How to replicate:
-> https://dev-vue-polkadot.netlify.com/#/settings select polkadot 
-> https://dev-vue-polkadot.netlify.com/#/addressbook and paste one of your valid address, delete one-two-three chars from address, paste new one address
Expected error: identicon is the same one, not new one.
Right behaviour: should generate new one icon

**Comment by vikiival** [comment]
Fixed with [release](https://github.com/vue-polkadot/vue-ui/commit/5991d8cb8d28b2528eb37884c46b39c52b025b71) 0.0.7
