### ISSUE TITLE
Update rollup to 2.1.0 in vue-keyring

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/vue-ui#26]
Right now there is rollup 1.21.4 and recent version is 2.1.0

**Comment by vikiival** [comment]
@yangwao is this fixed by using `tsc` ?

**Comment by yangwao** [comment]
Yes and No. 
But yes, let's stick with tsc, for now, to continue on other things.

Looks like problem is deeper than we could expect. 
* https://github.com/ezolenko/rollup-plugin-typescript2/issues/217
* https://github.com/acornjs/acorn-private-class-elements/pull/10#issuecomment-601340999
